//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAML2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAML2.TraceMessages", typeof(TraceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact created: {0}.
        /// </summary>
        internal static string ArtifactCreated {
            get {
                return ResourceManager.GetString("ArtifactCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact redirect received: {0}.
        /// </summary>
        internal static string ArtifactRedirectReceived {
            get {
                return ResourceManager.GetString("ArtifactRedirectReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact resolved: {0}.
        /// </summary>
        internal static string ArtifactResolved {
            get {
                return ResourceManager.GetString("ArtifactResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving artifact &quot;{0}&quot; from identity provider &quot;{1}&quot; endpoint &quot;{2}&quot;.
        /// </summary>
        internal static string ArtifactResolveForKnownIdentityProvider {
            get {
                return ResourceManager.GetString("ArtifactResolveForKnownIdentityProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact resolve received: {0}.
        /// </summary>
        internal static string ArtifactResolveReceived {
            get {
                return ResourceManager.GetString("ArtifactResolveReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending response to artifact resolve request &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string ArtifactResolveResponseSent {
            get {
                return ResourceManager.GetString("ArtifactResolveResponseSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact response received: {0}.
        /// </summary>
        internal static string ArtifactResponseReceived {
            get {
                return ResourceManager.GetString("ArtifactResponseReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion found: {0}.
        /// </summary>
        internal static string AssertionFound {
            get {
                return ResourceManager.GetString("AssertionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion being parsed.
        /// </summary>
        internal static string AssertionParse {
            get {
                return ResourceManager.GetString("AssertionParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully parsed Assertion: {0}.
        /// </summary>
        internal static string AssertionParsed {
            get {
                return ResourceManager.GetString("AssertionParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion prehandler called.
        /// </summary>
        internal static string AssertionPrehandlerCalled {
            get {
                return ResourceManager.GetString("AssertionPrehandlerCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing assertion: {0}.
        /// </summary>
        internal static string AssertionProcessing {
            get {
                return ResourceManager.GetString("AssertionProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttrQuery assertion received: {0}.
        /// </summary>
        internal static string AttrQueryAssertionReceived {
            get {
                return ResourceManager.GetString("AttrQueryAssertionReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttrQuery sent to &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string AttrQuerySent {
            get {
                return ResourceManager.GetString("AttrQuerySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience restriction validated for intended URIs {0} against allowed URIs {1}.
        /// </summary>
        internal static string AudienceRestrictionValidated {
            get {
                return ResourceManager.GetString("AudienceRestrictionValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthRequest sent for identity provider &quot;{0}&quot; using binding &quot;{1}&quot;.
        /// </summary>
        internal static string AuthnRequestPrepared {
            get {
                return ResourceManager.GetString("AuthnRequestPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthnRequest sent: {0}.
        /// </summary>
        internal static string AuthnRequestSent {
            get {
                return ResourceManager.GetString("AuthnRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common domain cookie received: {0}.
        /// </summary>
        internal static string CommonDomainCookieReceived {
            get {
                return ResourceManager.GetString("CommonDomainCookieReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect to SignOn endpoint found in Common Domain Cookie.
        /// </summary>
        internal static string CommonDomainCookieRedirect {
            get {
                return ResourceManager.GetString("CommonDomainCookieRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting to Common Domain for identity provider discovery.
        /// </summary>
        internal static string CommonDomainCookieRedirectForDiscovery {
            get {
                return ResourceManager.GetString("CommonDomainCookieRedirectForDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect to SignOn endpoint &quot;{0}&quot;.
        /// </summary>
        internal static string CommonDomainCookieRedirectNotFound {
            get {
                return ResourceManager.GetString("CommonDomainCookieRedirectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EncryptedAssertion Decrypted: {0}.
        /// </summary>
        internal static string EncryptedAssertionDecrypted {
            get {
                return ResourceManager.GetString("EncryptedAssertionDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting EncryptedAssertion.
        /// </summary>
        internal static string EncryptedAssertionDecrypting {
            get {
                return ResourceManager.GetString("EncryptedAssertionDecrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EncryptedAssertion found: {0}.
        /// </summary>
        internal static string EncryptedAssertionFound {
            get {
                return ResourceManager.GetString("EncryptedAssertionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity provider not found. Redirecting for identity provider selection.
        /// </summary>
        internal static string IdentityProviderRedirect {
            get {
                return ResourceManager.GetString("IdentityProviderRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity provider retreived from Common Domain Cookie: {0}.
        /// </summary>
        internal static string IdentityProviderRetreivedFromCommonDomainCookie {
            get {
                return ResourceManager.GetString("IdentityProviderRetreivedFromCommonDomainCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity provider retreived from known providers: {0}.
        /// </summary>
        internal static string IdentityProviderRetreivedFromDefault {
            get {
                return ResourceManager.GetString("IdentityProviderRetreivedFromDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity provider retreived from IDPChoiceParamater: {0}.
        /// </summary>
        internal static string IdentityProviderRetreivedFromQueryString {
            get {
                return ResourceManager.GetString("IdentityProviderRetreivedFromQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting to idpSelectionUrl for selection of identity provider: {0}.
        /// </summary>
        internal static string IdentityProviderRetreivedFromSelection {
            get {
                return ResourceManager.GetString("IdentityProviderRetreivedFromSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Logout Actions.
        /// </summary>
        internal static string LogoutActionsExecuting {
            get {
                return ResourceManager.GetString("LogoutActionsExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout handler called.
        /// </summary>
        internal static string LogoutHandlerCalled {
            get {
                return ResourceManager.GetString("LogoutHandlerCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully parsed Logout request: {0}.
        /// </summary>
        internal static string LogoutRequestParsed {
            get {
                return ResourceManager.GetString("LogoutRequestParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing Logout request POST binding message: {0}.
        /// </summary>
        internal static string LogoutRequestPostBindingParse {
            get {
                return ResourceManager.GetString("LogoutRequestPostBindingParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout request received: {0}.
        /// </summary>
        internal static string LogoutRequestReceived {
            get {
                return ResourceManager.GetString("LogoutRequestReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing Logout request Redirect binding message with signature algorithm {1} and signature {2}: {0}.
        /// </summary>
        internal static string LogoutRequestRedirectBindingParse {
            get {
                return ResourceManager.GetString("LogoutRequestRedirectBindingParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout request sent for identity provider &quot;{0}&quot; using &quot;{1}&quot; binding: {2}.
        /// </summary>
        internal static string LogoutRequestSent {
            get {
                return ResourceManager.GetString("LogoutRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully parsed Logout response: {0}.
        /// </summary>
        internal static string LogoutResponseParsed {
            get {
                return ResourceManager.GetString("LogoutResponseParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing Logout response POST binding message: {0}.
        /// </summary>
        internal static string LogoutResponsePostBindingParse {
            get {
                return ResourceManager.GetString("LogoutResponsePostBindingParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout response received.
        /// </summary>
        internal static string LogoutResponseReceived {
            get {
                return ResourceManager.GetString("LogoutResponseReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing Logout response Redirect binding message with signature algorithm {1} and signature {2}: {0}.
        /// </summary>
        internal static string LogoutResponseRedirectBindingParse {
            get {
                return ResourceManager.GetString("LogoutResponseRedirectBindingParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout response sent: {0}.
        /// </summary>
        internal static string LogoutResponseSent {
            get {
                return ResourceManager.GetString("LogoutResponseSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata document being created.
        /// </summary>
        internal static string MetadataDocumentBeingCreated {
            get {
                return ResourceManager.GetString("MetadataDocumentBeingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata document successfully created.
        /// </summary>
        internal static string MetadataDocumentCreated {
            get {
                return ResourceManager.GetString("MetadataDocumentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No replay attack detected.
        /// </summary>
        internal static string ReplaceAttackCheckCleared {
            get {
                return ResourceManager.GetString("ReplaceAttackCheckCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for replay attack.
        /// </summary>
        internal static string ReplayAttackCheck {
            get {
                return ResourceManager.GetString("ReplayAttackCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully decoded SamlResponse: {0}.
        /// </summary>
        internal static string SamlResponseDecoded {
            get {
                return ResourceManager.GetString("SamlResponseDecoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SamlResponse decoding.
        /// </summary>
        internal static string SamlResponseDecoding {
            get {
                return ResourceManager.GetString("SamlResponseDecoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SamlResponse received: {0}.
        /// </summary>
        internal static string SamlResponseReceived {
            get {
                return ResourceManager.GetString("SamlResponseReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing SignOn Actions.
        /// </summary>
        internal static string SignOnActionsExecuting {
            get {
                return ResourceManager.GetString("SignOnActionsExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignOn handler called.
        /// </summary>
        internal static string SignOnHandlerCalled {
            get {
                return ResourceManager.GetString("SignOnHandlerCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully processed signon request for &quot;{1}&quot; using NameIdFormat &quot;{2}&quot; for session &quot;{0}&quot;.
        /// </summary>
        internal static string SignOnProcessed {
            get {
                return ResourceManager.GetString("SignOnProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing SOAP message: {0}.
        /// </summary>
        internal static string SOAPMessageParse {
            get {
                return ResourceManager.GetString("SOAPMessageParse", resourceCulture);
            }
        }
    }
}
